### PR TITLE
Tutorial: Static Equilibrium proposal

### PR DESCRIPTION
**Pull request by h2o-DS**
I wrote this tutorial for introducing vector algebra for solving static equilibrium physics problems. Uses NumPy for linear algebra and matplotlib for visualizations.

### CODE REVIEW

**Comment by melissawm** [comment]
Hello @h2o-DS ! Sorry for the delay in doing this - we were still trying to understand what the best option for reviewing content would be. We have finally settled on converting `.ipynb` files to `.md`, with the help of Jupytext. This has the advantage of generating easy to diff markdown files, while you can still open that markdown file locally using Jupyter (you just need to install jupytext for that to work) and have it execute as a regular notebook.

Is it ok if I do this conversion, keeping your name as author and push the changes to your branch? Thanks!

**Comment by h2o-DS** [comment]
Hello @melissawm . Feel free to do the conversion. I can do so if need be.

Thank you!

**Comment by melissawm** [comment]
Hi @h2o-DS ! I can't seem to be able to push changes to your pull request because it was made against your master branch. 

Would you be able to pair this file with a markdown file following [these instructions](https://github.com/numpy/numpy-tutorials/blob/2142d10c6969af6b94d94a37ec7320e170ae3eb6/content/pairing.md#pair-your-notebook-files-ipynb-and-md)? 

If you have troube or would like further instructions, please let me know! Once the `.md` file is created, it would also be nice to add it to the `/site/index.md` table of contents. Thank you!

**Comment by melissawm** [comment]
Closing in favor of #61 .

**Pull request closed without merging**
