### PR TITLE
CI: Make sphinx-build more strict

### PR DESCRIPTION
**Pull request by rossbar**
Related to #51.

Checking that CI fails with execution error.

### CODE REVIEW

**Comment by rossbar** [comment]
Okay, I'm marking this ready for review. This PR updates the `sphinx-build` command in the circle CI job to make the error checking much more stringent. The sphinx build now uses the `-W` flag which will treat warnings as errors. This is primarily to catch notebook execution problems, but will also cause the CI to trip on any other sphinx warning. It also activates `nitpicky` mode to catch broken sphinx references.

As discussed in #51, I am +1 on also activating `nbval` for additional testing of the notebooks, but will leave that for a separate PR.

Note that this also bumps the cell execution timeout to 10 minutes so that the deep learning examples can run on the CI hardware. This can be tweaked back down in e.g. #54 along with the other changes to address very long-running notebooks. Note also that *I think* there's probably a way to persist the `jupyter-cache` across runs in circle CI so that only notebooks that have been changed are executed in the CI run for any given PR/push. Again, something for another PR.

**Comment by melissawm** [comment]
Thanks, @rossbar ! Looks reasonable to me.

**Comment by melissawm** [comment]
Something is wrong with [one of the dependencies of myst-parser](https://app.circleci.com/pipelines/github/numpy/numpy-tutorials/83/workflows/67cd52a4-30e6-413c-9cab-36ce9b7a0291/jobs/83), I think. @rossbar do you know how to solve this?

**Comment by rossbar** [comment]
Hm for whatever reason it looks like the pip resolver lands on an older markupsafe, which uses deprecated steuptools features in it's `setup.py`. It looks like that dependency needs a more stringent lower bound. Not sure where exactly it should be specified though, I'll see if I can disentangle it.

**Pull request merged**
