### PR TITLE
Update tutorial titles

### PR DESCRIPTION
**Pull request by guan404ming**
- clarifying that the notebooks are tutorials on NumPy Features and NumPy Applications

- ref: https://github.com/numpy/numpy/issues/26768

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
My 2 cents: the proposed addition of "Tutorials of" is redundant, as this is already explicitly a tutorials site. I'm -0.5 on changing the titles but will readily acquiesce if other reviewers prefer it!

**Comment by melissawm** [comment]
I agree with @rossbar, I think this is a bit redundant.

**Comment by guan404ming** [comment]
Thanks for the reviews! I added "Tutorials of" because directly going to the [feature page](https://numpy.org/numpy-tutorials/features.html) and [application page](https://numpy.org/numpy-tutorials/applications.html) doesn't clearly indicate it's a tutorial which may cause some confusion. But I'm open to everyone's opinions. Thanks again!

**Comment by bsipocz** [comment]
I also agree with the other maintainers. 

However, maybe we can have a different logo flavour, after all it doesn't link back to https://numpy.org but to https://numpy.org/numpy-tutorials/

**Comment by guan404ming** [comment]
I totally agree that having a different logo will prevent confusion. Thanks a lot for your time, everyone. I'll close this PR now~

**Pull request closed without merging**
