### PR TITLE
Ensure all tutorials use the recommended `Generator` API for random number generation

### PR DESCRIPTION
**Pull request by rossbar**
Updates any usage of `np.random` in the tutorials to use the newer, recommended (as of 1.17) API for the random package. This also required some rewording in the text, so please pay close attention when checking that the text changes didn't distort the original intended meaning.

### CODE REVIEW

**Comment by mattip** [comment]
Build failed with
```
WARNING: Execution Failed with traceback saved in /home/circleci/repo/site/_build/html/reports/tutorial-deep-learning-on-mnist.log
```

**Comment by melissawm** [comment]
This is still the MNIST download that is failing. I think we'll need to either disable this from CI for now, or remove that command entirely.

**Comment by rossbar** [comment]
Yeah the data cache on CI appears to have expired - it looks like it only lasts for 15 days, which is (as demonstrated) not adequate for our purposes.

**Comment by mattip** [comment]
Could you break this into two PRs: one for the mnist tutorial and one for all the rest so we can move forward?

**Comment by rossbar** [comment]
Unfortunately splitting it up won't help - all notebooks are run as part of the CI. We can cache the execution, but the caches expire quickly.

I'm going to create a different data mirror for the mnist data and point to that. It won't be perfect, but anything should be more reliable than the current data source.

**Comment by melissawm** [comment]
Maybe from [Kaggle](https://www.kaggle.com/c/digit-recognizer/data)?

**Comment by melissawm** [comment]
Ok, this works for now, so I'm merging so we can move forward. Thanks, @rossbar !

**Pull request merged**
