### PR TITLE
Lang

### PR DESCRIPTION
**Pull request by gitsava**

### CODE REVIEW

**Comment by rkern** [comment]
Did you mean to make a PR into your own fork?

**Comment by gitsava** [comment]
Yes, I'm want to replace it with the local language, namely Indonesian in the documentation

**Comment by gitsava** [comment]
may i add it to my repo

**Comment by rgommers** [comment]
> may i add it to my repo

sure, that'd be great. As I mentioned on gh-109 we are not yet ready to accept translations in this repo, but doing it on your own fork is perfectly fine.

**Comment by gitsava** [comment]
> > may i add it to my repo
> 
> sure, that'd be great. As I mentioned on [gh-109](https://github.com/numpy/numpy-tutorials/issues/109) we are not yet ready to accept translations in this repo, but doing it on your own fork is perfectly fine.

thank you

**Pull request closed without merging**
