### PR TITLE
MAINT: Pin gym[atari] version

### LINKED ISSUE #87: atari-py ROM configuration
The latest atari-py wheels break the pong tutorial with an exception about needing to install/configure appropriate ROMS. This is a known issue: open-ai/atari-py#79. Proposed workaround is to use an older version of atari-py==0.2.5 as suggested [here](https://github.com/openai/atari-py/pull/79#issuecomment-849927798), but this requires local building of the wheels, which is at the core of #69.

In the long run, it would be great if we could switch to using the newer atari-py wheels and figure out the minimal ROM configuration to get the example working sustainably again.

### PR DESCRIPTION
**Pull request by melissawm**
This fixes CI but doesn't totally get all of #87 yet.

### CODE REVIEW

**Comment by rossbar** [comment]
FTR this shouldn't have any affect on the CI, since the workflow uses `pip` (i.e. requirements files) rather than `conda`. +1 for the change though as we need to keep `requirements.txt` and `environment.yml` in sync (a bot that did this automatically would be great!)

The CI failures are related to failing to grab some Debian packages required to build the atari-py wheel locally. Maybe try adding `sudo apt-get update` prior to the line that `apt-get`'s cmake and ffmpeg?

**Comment by melissawm** [comment]
Ah - we were having a failing run on CI because atari-py (or gym) couldn't fetch the rom with the new version, but this other failure is also weird. Let me do that.

**Comment by melissawm** [comment]
Ok - I see this warning on CircleCI: https://circleci.com/docs/2.0/circleci-images/

*Legacy images with the prefix "circleci/" will be deprecated on December 31, 2021. For faster builds, upgrade your projects with next-generation convenience images. *

It might be worth just updating to the new `cimg/python:3.8` image instead?

**Comment by rossbar** [comment]
Yeah definitely, though that will also probably necessitate even more `apt-get`-ing because IIRC the `python` images are stripped down to the bare minimum needed to support Python.

We need to do it anyways so +1 for doing it here.

**Comment by melissawm** [comment]
It works! :tada:

**Review by rossbar — APPROVED** [review]
LGTM, thanks for chasing down the right recipe @melissawm !

It'd be great to tear out all the build-our-own-wheels stuff eventually, but we'll have to tackle #87 to get there

**Pull request merged**
