### PR TITLE
MAINT: move non-executable content to its own category.

### PR DESCRIPTION
**Pull request by rossbar**
As discussed in the previous documentation meeting, this PR implements the "medium-term" solution to the tutorials that have been added but are not currently executable.

Essentially, this moves the RL and NLP tutorials to a separate category that I called "articles" (naming suggestions welcome) and adds some text that these are not tested. I've also added admonitions soliciting contributions from any one who might be interested in helping to make them fully executable.

### CODE REVIEW

**Comment by bsipocz** [comment]
> Essentially, this moves the RL and NLP tutorials to a separate category that I called "articles" (naming suggestions welcome) and adds some text that these are not tested. I've also added admonitions soliciting contributions from any one who might be interested in helping to make them fully executable.

What are the limitations on making them executable? Too many dependencies/resource requirements for being practical, or some other reasons?

**Comment by rossbar** [comment]
> What are the limitations on making them executable? Too many dependencies/resource requirements for being practical, or some other reasons?

For the reinforcement learning tutorial, it's a dependency issue - specifically licensing of ROMs which have EULA's/potential licensing concerns. See e.g. #87 for more details.

For the NLP tutorial it was mostly a matter of data hosting which was the bottleneck, then the tutorial was merged provisionally with the intention of following up once a tutorial data hosting solution had been worked out. Since it wasn't executable when merged, this one would also need review.

**Comment by bsipocz** [comment]
Oh, wonderful.

**Review by bsipocz — APPROVED** [review]

**Comment by rossbar** [comment]
@melissawm just a quick ping here if you have any thoughts on this reorganization proposal!

**Review by melissawm — APPROVED** [review]
Sorry for the delay, this looks good to me. I wonder if we should expand on the reason why these tutorials are not executable at the index page, too. We could just copy the

```
This article is not currently tested due to licensing/installation issues with
the underlying `gym` and `atari-py` dependencies.
Help improve this article by developing an example with reduced dependency
footprint!
```

message from within the tutorial to the index page.

**Comment by rossbar** [comment]
Thanks all - I'll go ahead and get this in. Once the categories are separated, if anyone would like to add/adjust the admonitions, please follow-up with an issue/PR!

**Pull request merged**
