### PR TITLE
imageio.imread replaced with imageio.v2.imread

### PR DESCRIPTION
**Pull request by rifatrakib**
`imageio.imread` is not supported anymore, `imageio.v2.imread` is suggested as a replacement from the module maintainers.

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
Thanks for the proposed update @rifatrakib .

The proposed change is failing, likely because `imageio` doesn't support lazy importing. From their docs, it looks like you'd need to do something like: `import imageio.v2 as iio`.

Also, it looks like there's also an `imageio.v3` now as well, which [seems to be recommended for new code](https://imageio.readthedocs.io/en/stable/reference/index.html#core-apis). Should we update to v3 instead?

**Comment by rifatrakib** [comment]
I am using Python 3.8.5 with conda, it worked perfectly fine in my setup. But since `v3` is the latest way of doing this, I will  make adjustments accordingly. Thanks for the feedback.

**Comment by rossbar** [comment]
Okay, it looks like a dependency resolution problem. We're getting very old versions of both Pillow (which is requiring a local wheel build, which is subsequently failing) and imageio (which explains why imageio.v2 or imageio.v3 fails - because these pkgs don't exist yet in imageio v2.9.0).

I suspect this is related to the `gym`/`ataripy` dependencies for the RL notebook. This change looks good, but unfortunately will be blocked until we fix this other dependency problem. If nothing else, this is a strong motivation to remove these unsupported dependencies, which I will try to do ASAP.

Thanks for the fixup @rifatrakib . Sorry it's not going as quickly as it should do to the nice can of worms you've inadvertently discovered!

**Review by rossbar — APPROVED** [review]
Now that #144 is in we can push this forward! Thanks again @rifatrakib !

**Pull request merged**
