### PR TITLE
Tutorials infrastructure: switch to sphinx+text-based notebook workflow

### PR DESCRIPTION
**Pull request by rossbar**
# Overview

Changes the workflow for the `numpy-tutorials` repo to use a text-based format for Jupyter notebooks and sphinx+[myst](https://github.com/executablebooks/MyST-NB) for running & testing the notebooks, and generating a static tutorials site.

The [text-based notebook format](https://myst-nb.readthedocs.io/en/latest/use/markdown.html) expresses notebooks in markdown rather than the typical json format associated with `.ipynb` files. This enables a workflow for submission and review that maps onto the standard GitHub reviewing workflow.

Authors can still submit content in `.ipynb` format - it will be converted to `.md` for review using [jupytext](https://jupytext.readthedocs.io/en/latest/formats.html#myst-markdown). Both html and downloadable notebooks (.ipynb) are generated as part of the build process. CircleCI has been configured to handle this on GitHub. A standard sphinx workflow can be used to run/evaluate changes locally (though users are not required to use the sphinx for authoring/reviewing!)

The [sphinx-book-theme](https://sphinx-book-theme.readthedocs.io/en/latest/index.html) is based on the `pydata-sphinx-theme` used in the main NumPy docs, and provides convenient buttons both for launching notebooks on cloud services (e.g. binder & jupyterhub) as well as downloading notebooks to run locally.

# Todo
 - [x] Decide where/how to host the static site
 - [x] Update `site/index.md`, which is the landing page for the sphinx site (see faa5368)
 - [ ] Update README (and landing page) with instructions for new workflow (new gifs?)
 - [x] Clean up sphinx warnings related to notebook execution (see dc313fe)
 - [x] Review `content/*.md` and remove any leftover cruft (e.g. colab metadata) (see 9915375)
 - [x] Incorporate executablebooks/sphinx-book-theme#241 (or related) to get downloads working for both `.ipynb` and `.md` formats

## Post merge
 - [ ] Verify the [binder launch buttons are configured correctly](https://sphinx-book-theme.readthedocs.io/en/latest/launch.html)
 - [ ] Activate circleCI configuration for `numpy/numpy-tutorials` and deactivate it rossbar's fork
 - [ ] Update existing PRs with new content to use new workflow

### CODE REVIEW

**Comment by melissawm** [comment]
Thanks, @rossbar ! I'll give it a try locally and see how that goes.

Could the static site be served through github pages? 

I can do the README update with new gifs.

**Comment by rossbar** [comment]
> Could the static site be served through github pages?

That would be my preference!

> I can do the README update with new gifs.

Great :) I didn't intend for the TODO's to be blockers or anything, just a running list of ideas that I had while putting this together, so no pressure!

**Comment by melissawm** [comment]
I tried this locally and this looks really good. Now for the plan:
- I think hosting on github pages is probably the way to go, although I don't have a lot of experience there. Any advice is appreciated.
- I'll update the README in a follow-up, so the workflow is decided and I can redo the gifs and update instructions.
- This - *Incorporate executablebooks/sphinx-book-theme#241 (or related) to get downloads working for both .ipynb and .md formats* - would be very nice, but not a blocker. If people really want the ipynb files before that is done we can always include a link to the raw github files in the .md. Let's wait and see if that's merged before we get our own things sorted.
- I'll trust you with the CI, but the workflow in https://github.com/rossbar/numpy-tutorials/pull/2 seems pretty reasonable.

Thank you so much, @rossbar ! I think this is an improvement over ReviewNB which, unfortunately, doesn't look ready to use.

**Comment by rossbar** [comment]
> I think hosting on github pages is probably the way to go, although I don't have a lot of experience there. Any advice is appreciated.

I agree - I'll set up the CI/CD to deploy to github pages on merge (similar to numpy devdocs). Down the road, I think we can still use github pages to host but redirect somewhere else (e.g. somewhere on numpy.org) pretty easily if that's what the community decides to do.

> I'll trust you with the CI, but the workflow in rossbar#2 seems pretty reasonable.

I expect there will be plenty to tweak as we try this out. Fortunately the set of tools is pretty flexible so I think we can accommodate a lot of different approaches.

I'll update the CI config this week for deployment. LMK if anything else crops up that needs attention!

**Comment by mattip** [comment]
The numpy devdocs is a bit strange in that there is a dedicated repo just for the rendered docs. Another option, and one that projects seem to be adpoting more, is to have a dummy branch inside the repo, like `site` or `gh-pages`. Then you do something like this on merges
```
push doc
make html
popd
git checkout gh-pages
rm -rf docs/*
cp -r doc/build/html/* docs
git add docs       # both adds and removes content
git commit -m"automatic build"
git push
```
For a sample github-action based workflow that pushes built documents to a branch in the current repo see [here](https://github.com/Quansight/numpy-threading-extensions/blob/main/.github/workflows/tox.yml#L64)

This example has a few other things on the `site` branch:
- there is a directory for each version of the repo under `docs`. You probably don't need that here
- since there directories are versioned, there is a `stable` symlink to the last release, and an `index.html` page that redirects to `stable`. Again, you probably don't need that here.

We did have a bit of a problem getting it going, since the PR tries to do `git push`, and the PR was from a fork of the repo, so during the PR CI runs it kept failing. Once we did the PR from a branch in the repo itself, rather than from  a fork, it all JustWorks.

If you are concerned about the size of the repo, you can do destructive commits to `site` instead of additive ones using force-push. It will mess up people who check out the `site` branch, but :shrug:

**Comment by mattip** [comment]
Maybe split the PRs: only build in this PR and then in another one deploy?

**Comment by melissawm** [comment]
I agree with @mattip . As far as I'm concerned, this is good for merging. But it would be useful to have the opinion of others more experienced in CI and this kind of workflow.

**Review by melissawm — APPROVED** [review]

**Comment by mattip** [comment]
Someone with admin permissions and a circleci account needs to add the needed integrations to get this to work

**Comment by charris** [comment]
@mattip What needs to be done?

**Comment by rossbar** [comment]
I think I have the necessary permissions for the CircleCI. I also have to disable the CircleCI on my own fork for it to take effect. I'm happy to do so after merging.

**Comment by melissawm** [comment]
Hello folks! Finally merging this - thanks @rossbar and all who contributed to the discussions. This may mean that our README is outdated for a while, so I'll add a note there explaining we're still figuring this out.

**Pull request merged**
