### PR TITLE
Tiled layout w/ images for front page

### PR DESCRIPTION
**Pull request by rossbar**
I had the idea to try to replicate a gallery-like layout on the landing page, similar to what you would get from e.g. `sphinx-gallery`. I think this is a really effective way to showcase the tutorials as the thumbnail helps summarize the tutorial and hopefully pique the readers' interest.

I couldn't find a tool that would create the gallery in the way I wanted with the necessary flexibility, so I created this manually by combining `sphinx-panels` for the thumbnail layout and the `glue` feature from `myst_nb` for creating the thumbnail content. The downside is that it takes a little extra effort to add a thumbnail (I will have to add the procedure to the contributing doc).

Since this is based on `sphinx-panels` I also added a couple examples of adding "badges" to the thumbnails as discussed in #7. Currently the badges are purely decorative, but we can (and should) make them linkable to indices of tutorials that share badges, though I'm not planning on pushing on that idea too much in this PR.

Anyways, feedback on the layout idea and the approach used to implement would be appreciated!

### CODE REVIEW

**Review by melissawm — COMMENTED** [review]
This looks really good, thanks @rossbar ! The only comment I have is about the alignment for the thumbnails in the panels - for example, for the fractal tutorial the image is at the top of the panel:

Screen Shot 2022-01-29 at 11 38 47 PM

Is this something that could be configured easily? Not a blocker but just a nice thing to have. Other than that, +1 on merging! 

In a follow-up we should definitely come up with a list of tags that don't grow indefinitely. Do you know if there's a way to filter the documents by those tags using sphinx? I've seen some discussion around using page metadata to generate indices but I've never personally done it before. Something for the future perhaps...

**Comment by rossbar** [comment]
af82e8e includes some very rudimentary instructions on creating the thumbnail with sphinx-panels. I only added it to the `contributing.md` so it's not in the readme, but I'd like to deduplicate all of that content in a followup PR.

**Comment by melissawm** [comment]
@rossbar I'd love to merge this, is there anything else you'd like to do before we put it in?

**Comment by rossbar** [comment]
One drawback of `glue` is that it [does not currently support alt-text](https://github.com/executablebooks/MyST-NB/issues/211), which means some of the thumbnails on the front page wouldn't have alt-text. I'm not sure whether that's a blocker, but it'd be nice to have. The feature seems to be on `myst-nb`'s radar and will hopefully be incorporated soon. It'd also be nice to fix the thumbnail size, but I haven't looked at that yet - again, whether that's a blocker or a follow-up :shrug: .

Aside from those issues, nothing else comes to mind.

**Comment by rossbar** [comment]
I'm going to go ahead and close this one, as it's now pretty out of date due to inaction on my end (e.g. `sphinx-panels` has been replaced with `sphinx-design`). I still think this is a worthwhile endeavor but so much has changed in the underlying tooling that it's probably worth a fresh start.

Thanks for the feedback!

**Pull request closed without merging**
