### PR TITLE
Fully automate dev setup with Gitpod

### LINKED ISSUE #18: Set up gitpod
After the final format for the repo is decided and merged.

### PR DESCRIPTION
**Pull request by melissawm**
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitHub and GitLab that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

Fixes #18

### CODE REVIEW

**Comment by melissawm** [comment]
I tried to cover basic instructions for using gitpod. It would be extremely useful if other people could test and see if I missed anything. Keep in mind gitpod is supposed to help people who are not very familiar with git, so while the instructions may seem more complicated than the usual method to us, they are (hopefully) easier to someone less experienced.

**Review by rgommers — COMMENTED** [review]
Thanks Melissa, looking forward to having GitPod support!

I tried this out; logging into GitPod and editing a README file was straightforward. The actual dev environment is missing though. Python is installed, but nothing else. Your instructions seem to say that it's for uploading a `.ipynb` file, but that can be done through the GitHub UI easily enough. So now that we only have notebooks in this repo, I think there's no purpose having GitPod here - there's no development to be done.

On the main repo though it would be awesome - the docker image should then contain an already built development version of NumPy.

**Comment by melissawm** [comment]
Thanks for the feedback! I guess the way forward would be to remove gitpod here and add it to the main repo once I figure out how to build the whole dev environment. However, I just got access to the beta of GitHub Codespaces and that seems exactly like gitpod, so I might put this off for a while and see if codespaces solves our problem. If it does it's probably better to have a first-party application instead of a third-party one. I'll close this PR and update the issue with this info as well.

**Comment by matthew-brett** [comment]
Just as a meta point - [over at JupyterLab](https://github.com/jupyterlab/team-compass/issues/80), we were worrying that it might be unhealthy for the ecosystem if Microsoft Visual Studio Code starts to dominate in the online notebook market.  Is that a reason to prefer Gitpod, regardless of convenience?  I believe that Gitpod is [based on Theia](https://www.gitpod.io/blog/opensource), with a wider governance governance community than VSCode.

**Comment by rgommers** [comment]
That code to mind for me too - and I actually quite liked the Gitpod experience, it's smooth.

**Comment by melissawm** [comment]
Good point. This may be something to discuss in a community meeting, I'll make sure to bring it up.

**Pull request closed without merging**
