### PR TITLE
ENH: add tox.ini to generize test setup

### LINKED ISSUE #141: Add testing configuration for running pytest locally
#132 added notebook smoketesting with `pytest-nbval` to CI, but didn't add any pytest configuration nor a way to automatically handle installing testing dependencies. Handling this configuration correctly will make it easier for users to smoketest notebooks locally with pytest. #139 is related as it should also be handled via pytest config. One idea would be to use `tox.ini` - see https://github.com/numpy/numpy-tutorials/pull/132#issuecomment-1152632942.

### PR DESCRIPTION
**Pull request by bsipocz**
This should help local testing, etc.

To close #141

It also addresses (potentially), and close https://github.com/numpy/numpy-tutorials/issues/139

TODO (but opening the PR now to see whether this indeed works on GHA not just locally): 

- [ ] rethink the matrix and think about version combinations that make sense
- [x] add dev version testing to the matrix
- [ ] use tox for the other CI configs, including building the HTML pages

### CODE REVIEW

**Comment by bsipocz** [comment]
hmm, `tox -e test` works locally, not sure what goes wrong with it (though in other projects I don't have multidimensional python version, but add that to the environment).

**Comment by bsipocz** [comment]
@rossbar - Far from perfect, and finished, but maybe it's better to include more things (e.g. see the checkboxes above) into tox incrementally.

**Comment by bsipocz** [comment]
@rossbar @melissawm - Far from perfect, and finished, but maybe it's better to include more things (e.g. see the checkboxes above) into tox incrementally.

**Comment by bsipocz** [comment]
Let's get this in, we can always improve incrementally.

**Comment by melissawm** [comment]
Thanks, @bsipocz !!

**Pull request merged**
