### PR TITLE
Removed id markup and fixed item numbering for Pong tutorial.

### LINKED ISSUE #74: Weird markup in Pong tutorial cells
The current version of https://github.com/numpy/numpy-tutorials/blob/main/content/tutorial-deep-reinforcement-learning-with-pong-from-pixels.md has strange markup like this in many places:
```
+++ {"id": "3i7nPwJw_gKw"}
```

### PR DESCRIPTION
**Pull request by melissawm**
Fixes #74

### CODE REVIEW

**Review by rossbar — COMMENTED** [review]
+1 for removing the "id" metadata.

One thing to note is that the `+++` markup indicates a cell break in the notebook, so removing them will merge things into a single cell. Generally this is fine, though it's worth noting that there are some situations where it makes a difference: for example, if there are two sequential cells with enumerated lists, the numbering will not be reset if the `+++` separating them is removed. AFAICT there were no differences here (and the instances of enumeration are removed from this PR anyways) but I wanted to check with @8bitmp3 - do you have a strong feeling that you'd like to keep the original cell breaks?

**Comment by 8bitmp3** [comment]
Thanks @melissawm @rossbar The "id" metadata is introduced after the jupyter2markdown conversion, isn't it? As long as the users can keep up with the instructions (and it looks the same in Markdown with and without `+++ id...`), I'm OK with these changes 👍

**Review by rossbar — APPROVED** [review]
LGMT thanks @melissawm !

**Comment by rossbar** [comment]
> The "id" metadata is introduced after the jupyter2markdown conversion, isn't it? 

Maybe... is jupyter2markdown a specific tool? AFAIK `jupytext` doesn't add any cell metadata by default. My guess would be that the id metadata is carried over from whatever platform the tutorial was originally written in. For example, colab adds colab-specific metadata to cells.

**Comment by melissawm** [comment]
Ah - that would explain it! I did check to see if there would be problems with the cells but as far as I can tell the notebook renders fine.

**Comment by rossbar** [comment]
CI problems unrelated (again), so in it goes. Thanks @melissawm & @8bitmp3 !

**Pull request merged**
