### PR TITLE
Adds github action to use nbval/pytest to validate notebooks.

### LINKED ISSUE #3: Add CI job that covers notebook content
https://github.com/reviewNB/treon could work as the tool to validate notebook, it looks like it has extra features like running examples as doctests that could be useful.

The basic "run a notebook" is `jupyter nbconvert --to notebook --inplace --execute somenotebook.ipynb`.

I don't know what CI setups other projects use.

### PR DESCRIPTION
**Pull request by melissawm**
This uses [nbval](https://github.com/computationalmodelling/nbval) to validade notebooks using pytest through a github action. 

Fixes #3

### CODE REVIEW

**Comment by melissawm** [comment]
Is anyone opposed to this PR being merged or can help me figure out if there's a better way of doing it?

**Comment by rgommers** [comment]
This is about as simple as CI gets, so would be good to try. I had expected the action to run on this PR though - I guess that doesn't work for GH Actions, so you tried on your local fork?

**Comment by melissawm** [comment]
Yes, I did try it on my own fork and it worked great. I don't know what's the best strategy to test these things on the main repo, I don't know if there's a way to trigger it before it is merged..

**Comment by rgommers** [comment]
Okay, in it goes then. Thanks Melissa!

**Pull request merged**
