### PR TITLE
Meta: fix tutorial attribution on GitHub

### PR DESCRIPTION
**Pull request by rossbar**
## The problem

GitHub shows the commit history *for each file*. It is not unreasonable for people to look at that history for attribution information. However, if there was e.g. a file conversion or renaming in the history, the *per-file* commit history doesn't necessarily reflect the true authorship of the tutorial.

For example, look at the [history for `mooreslaw-tutorial.md`](https://github.com/numpy/numpy-tutorials/commits/master/content/mooreslaw-tutorial.md). This tutorial was written by @cooperrc  , but since I converted it from .ipynb -> .md in the review process (and didn't use the `--author` flag when committing), the first commit in the history shown for this file doesn't reflect [the original author's work](https://github.com/numpy/numpy-tutorials/commits/ac9c8f01e67dbe4edce04fe5a66317bee319cfe6/content/mooreslaw-tutorial.ipynb)

## A potential fix

Since the problem is with viewing the history *for individual files* in GitHub, we can work around this problem without needing to rebase/modify the history by changing the tutorial file names, and making sure to commit with the `--author` flag for appropriate attribution. This PR does so by renaming each tutorial, replacing `-`'s with `_`'s. The procedure looks something like:

```bash
git mv mooreslaw-tutorial.md mooreslaw_tutorial.md
git commit --author="Ryan C Cooper <cooperrc@users.noreply.github.com>" -m "Original tutorial author: Ryan C Cooper <cooperrc@users.noreply.github.com>"
```

This converts the per-file history in the github interface from [this](https://github.com/numpy/numpy-tutorials/commits/master/content/mooreslaw-tutorial.md) to [this](https://github.com/rossbar/numpy-tutorials/commits/fix-attribution/content/mooreslaw_tutorial.md), which is much more accurate in terms of attribution.

From that point on, whenever anyone modifies a tutorial, the commits will show up in the history for that file (as long as it isn't renamed), but this commit will always be the root, reflecting the original authorship.

Note that in the updated history I linked above for the Moore's law tutorial, I'm still shown as the "committer". We can get rid of that as well: instead of merging this PR, each author can follow the procedure above for their own tutorials and submit their own PR. In that case, you shouldn't even need to use the `--author` flag.

LMK what you think. I arbitrarily chose changing `-` -> `_` in the filenames, but any change to the file name will work. The upside is that the commit histories for both the whole project *and* each file should better capture attribution, and the only downside is an extra meta-commit or two in the history (this works even if you squash-merge).

Note also that this is a one-shot fix. We can avoid the need for doing this again in the future by making sure to use the `--author` flag whenever a file is being renamed/converted to a new format.

### CODE REVIEW

**Comment by charris** [comment]
If you use `git mv` to rename files the commit history will be kept. Doesn't help with conversions, though.

**Comment by rossbar** [comment]
> If you use git mv to rename files the commit history will be kept. Doesn't help with conversions, though.

Yup. The problem we were having (I think, assuming I understood the issue correctly) has more to do with the way GH displays the history in the web UI, not the commit history itself. The full history of all the changes is of course available via `git log` etc.

**Comment by melissawm** [comment]
Thank you, @rossbar for doing this. This looks good to me!

**Comment by mattip** [comment]
This is still marked as a draft

**Comment by rossbar** [comment]
> This is still marked as a draft

Yes, I wanted to hear from the original authors to see if this is a satisfactory fix to the problem. @8bitmp3 @cooperrc what do you think?

**Comment by cooperrc** [comment]
@rossbar, lools great. Thanks!

**Comment by 8bitmp3** [comment]
lgtm @rossbar

**Comment by melissawm** [comment]
All the issues raised here seem to be resolved, so I'm closing. Feel free to mention if you think otherwise. Thanks!

**Pull request closed without merging**
